### ISSUE TITLE
Better string handling

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1331]
Right now we use 2 QT functions to identify strings: `qtTrId` and `qsTrId`. They do the same thing in 2 different languages C++ and QML (js). Internally, these 2 functions call `QCoreApplication::translate` passing a nullptr as context. If the context is null, QT uses the filename as context. This is why we have a map between the string ID and the filename.

My proposal is to implement a `vpnTrId` function (or a better name). This function can receive a unique string ID.
The strings are taken from a configuration file containing unique string IDs and a context. For instance we could have (yaml syntax):

```
settings:
  - user: VPN Users
  - runOnBoot: Launch VPN app on Startup
  - withComments:
     - this is a string
     - this is the comment
```

from this, at compilation time, we generate the following strings:
* vpn.settings.user
* vpn.settings.runOnBoot
* vpn.settings.withComments

and it would be similar to write the following, but it would not be bonded to a particular source file:
```
//% "VPN User"
qtTrId("vpn.settings.user")
//% "Launch VPN app on Startup"
qtTrId("vpn.settings.runOnBoot")
//% "this is a string"
//: this is a comment
qtTrId("vpn.settings.withComments")
```

@flodolo @lesleyjanenorton @strseb thoughts?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-729)
